---
- name: Retry failed allocations
  uri:
    url: "http://{{ es_master }}:9200/_cluster/reroute"
    method: POST
    user: "{{ es_username }}"
    password: "{{ es_password }}"
    force_basic_auth: true
    body_format: json
    body:
      retry_failed: true
    status_code: 200

- debug:
    msg: "Retry failed shard allocation completed."
