---
- name: Node Remediation
  hosts: es
  vars_files:
    - /u01/ansible/eda/vars/elasticsearch.yml
  gather_facts: false
  tasks:
  - name: Renew certificate
    import_tasks: ../security/renew_certificate.yml

  - name: Reload SSL configuration
    import_tasks: ../security/reload_ssl.yml

  - name: Restart security services
    import_tasks: ../security/restart.yml

  - name: Verify security configuration
    import_tasks: ../security/verify.yml
