---
- name: Update JVM heap
  become: true

  lineinfile:
    path: "{{ es_jvm_options }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: true

  loop:
    - regexp: "^-Xms"
      line: "-Xms{{ new_heap_size }}"
    - regexp: "^-Xmx"
      line: "-Xmx{{ new_heap_size }}"

- debug:
    msg: "Heap updated to {{ new_heap_size }}"
